JV2016-GruposW/src/accesoDatos/DatosException.java
JV2016-GruposW/src/modelo/ModeloException.java
JV2016-GruposW/src/util/UtilException.java

Se envia de nuevo,,,
Se han añadido tres nuevos tipos de excepciones para la gestion de errores en los paquetes .uti .modelo y .Datos.

excepciones en los paquetes modelo, util y datos.

---

JV2016-GruposW/src/accesoUsr/UsrException.java

Grupo: 0 - A. Juan Pérez
Se reinta...
Añade nuevo tpo excepción en el paquete .accesoUsr.

Nueva excepción en paquete .accesoUsr

---

JV2016-GruposW/src/modelo/Nif.java

Modificación nif con exception. Grupo 1: Tomás Buendía Alacid

Modificación nif con exception

---

JV2016-GruposW/src/modelo/Posicion.java

Alvaro Robles Andreu. Se añaden excepciones en la clase posición y se asegura que las
posiciones no sean negativas.

Alvaro Robles Andreu.

---

JV2016-GruposW/src/modelo/Correo.java

Grupo4 Cambios en Correo José María Hernández Martínez

Grupo4 Cambios en Correo José María Hernández Martínez

---

JV2016-GruposW/src/modelo/Usuario.java

Jose Miguel Solana Cases 
grupo 2

Añadidas excepciones a la clase Usuario

---

JV2016-GruposW/src/modelo/Persona.java

Actualiza la Clase Persona, agregando gestión de excepciones

Alejandro Sánchez - Grupo 3

---

JV2016-GruposW/src/modelo/SesionUsuario.java

grupo3 jose andres garcia

---

JV2016-GruposW/src/modelo/DireccionPostal.java

Antonio Alejandro Martinez Munar Grupo2

modificaciones primer cambio

---

JV2016-GruposW/src/accesoDatos/test/DatosPrueba.java
JV2016-GruposW/src/accesoDatos/test/DatosTest.java
JV2016-GruposW/src/accesoUsr/Presentacion.java

Grupo 0: AJP
Presentacion -> se actualiza para utilizar ModeloException.
DatosPrueba -> nueva clase para los datos de prueba.
DatosTest -> tests de la fachada de acceso a datos.

Presentacion -> se actualiza para utilizar ModeloException.

---

JV2016-GruposW/src/modelo/SesionUsuario.java

correccion de algunos errores en las excepciones de el constructor copia
y metodo clone

Amanda Iniesta Sepúlveda Grupo3

---

JV2016-GruposW/src/accesoDatos/Datos.java
JV2016-GruposW/src/accesoDatos/OperacionesDAO.java
JV2016-GruposW/src/accesoDatos/memoria/MundosDAO.java
JV2016-GruposW/src/accesoDatos/memoria/PatronesDAO.java
JV2016-GruposW/src/accesoDatos/memoria/SesionesDAO.java
JV2016-GruposW/src/accesoDatos/memoria/SimulacionesDAO.java
JV2016-GruposW/src/accesoDatos/memoria/UsuariosDAO.java

Grupo 0: AJP
Datos -> actualizada para utilizar interface OperacionesDAO
OperacionesDAO -> nueva interface para normalizar las operaciones de gestión de datos.
*DAO -> nueva versión de DAO's de almacenamineto en memoria.

Datos -> actualizada para utilizar interface OperacionesDAO

---

JV2016-GruposW/src/config/Configuracion.java

Grupo 0: AJP
Configuracion -> Nueva clase para gestionar la configuración del programa.

Configuracion -> Nueva clase para gestionar la configuración del

---

JV2016-GruposW/.project
JV2016-GruposW/src/accesoDatos/fichero/MundosDAO.java
JV2016-GruposW/src/accesoDatos/fichero/PatronesDAO.java
JV2016-GruposW/src/accesoDatos/fichero/Persistente.java
JV2016-GruposW/src/accesoDatos/fichero/SesionesDAO.java
JV2016-GruposW/src/accesoDatos/fichero/SimulacionesDAO.java
JV2016-GruposW/src/accesoDatos/fichero/UsuariosDAO.java

Grupo 0: AJP
Fichero de configuración y DAO's fichero

Fichero de configuración y DAO's fichero

---

JV2016-GruposW/src/modelo/test/NifTest.java

Modificación NifTest

---

JV2016-GruposW/src/modelo/test/PersonaTest.java
JV2016-GruposW/src/modelo/test/UsuarioTest.java

Grupo 0: AJP
Errores pendiente en la las clases test del modelo.

Errores pendiente en la las clases test del modelo.

---

JV2016-GruposW/jv.config

Grupo 0: AJP
Errores pendiente en la las clases test del modelo.

Faltaba el fichero de configiración.

---

JV2016-GruposW/.project
JV2016-GruposW/src/modelo/DireccionPostal.java
JV2016-GruposW/src/modelo/Persona.java
JV2016-GruposW/src/modelo/Usuario.java

Grupo 0: AJP
Las clases Usuario, Persona y DireccionPostal que producían errores relacionados con la validación de algunos de los atributos. También se restaura el nombre de proyecto original que se había alterado por error.

Sustituye Usuario, Persona y DireccionPostal que producian errores

---

JV2016-GruposW/src/accesoDatos/Presentacion.java
JV2016-GruposW/src/accesoDatos/fichero/MundosDAO.java
JV2016-GruposW/src/accesoDatos/fichero/PatronesDAO.java
JV2016-GruposW/src/accesoDatos/fichero/SimulacionesDAO.java
JV2016-GruposW/src/accesoDatos/memoria/MundosDAO.java
JV2016-GruposW/src/accesoDatos/memoria/PatronesDAO.java
JV2016-GruposW/src/accesoDatos/memoria/SimulacionesDAO.java
JV2016-GruposW/src/accesoDatos/test/DatosPrueba.java
JV2016-GruposW/src/accesoDatos/test/DatosTest.java
JV2016-GruposW/src/modelo/ClaveAcceso.java
JV2016-GruposW/src/modelo/Correo.java
JV2016-GruposW/src/modelo/Fecha.java
JV2016-GruposW/src/modelo/Formato.java
JV2016-GruposW/src/modelo/Mundo.java
JV2016-GruposW/src/modelo/Nif.java
JV2016-GruposW/src/modelo/Patron.java
JV2016-GruposW/src/modelo/Posicion.java
JV2016-GruposW/src/modelo/SesionUsuario.java
JV2016-GruposW/src/modelo/Simulacion.java

Grupo; 0 AJP
Actualización de la mayoría de las clases del modelo para unificar la validación y tratamineto de errores.
Actualización de Fecha y Formato
Actualización de DAO's memoria y fichero.

Actualización de la mayoría de las clases del modelo para unificar la

---

JV2016-GruposW/src/accesoUsr/vista/VistaSesionTexto.java

Grupo 3 - Yeray Pérez Pancorbo
Añade la clase accesoUsr.vista.VistaSesionTexto al proyecto.

Grupo 3 - Yeray Pérez Pancorbo

---

JV2016-GruposW/src/accesoDatos/fichero/SesionesDAO.java

Grupo4 Alejandro Navarro

---

JV2016-GruposW/src/accesoDatos/memoria/SimulacionesDAO.java

GRUPO 4 SIMULACIONDAO JUDITH

---

JV2016-GruposW/src/accesoUsr/vista/vistaSimulacionTexto.java

Creacion de la clase vistaSimulacionTexto

Alfonso pozo - grupo3

---

JV2016-GruposW/src/modelo/test/DireccionPostalTest.java

Daniel Abellán Segorbe Grupo 2

DireccionPostalTest-Daniel Abellán Segorbe

---

JV2016-GruposW/src/modelo/DireccionPostal.java

Antonio Manuel Cerezo Bermudez grupo 2

Correccion de returns

---

JV2016-GruposW/src/accesoUsr/control/ControlSesion.java

Clase controlSesion, con errores corregidos.

Grupo 3- Amanda Iniesta Sepúlveda y Alex Sánchez Jurado

---

JV2016-GruposW/src/JVPrincipal.java
JV2016-GruposW/src/accesoUsr/OperacionesVista.java
JV2016-GruposW/src/accesoUsr/OperacionesVistaSesion.java
JV2016-GruposW/src/accesoUsr/consola/VistaMenuPrincipal.java
JV2016-GruposW/src/accesoUsr/consola/VistaSesion.java
JV2016-GruposW/src/accesoUsr/consola/VistaSimulacion.java

Grupo 0; AJP
Añade interfaz OperacionesVista y actualiza las clases asociadas.

Añade interfaz OperacionesVista y actualiza las clases asociadas.

---

JV2016-GruposW/src/accesoDatos/memoria/MundosDAO.java

Actualización MundosDAO. Grupo 1. Tomás Buendía Alacid

Actualización MundosDAO

---

JV2016-GruposW/src/accesoDatos/fichero/SesionesDAO.java
JV2016-GruposW/src/accesoDatos/memoria/SesionesDAO.java

Correccion de las clases SesionesDAO

grupo4 Amanda Iniesta Sepúlveda

---

JV2016-GruposW/src/accesoUsr/swing/VistaPrincipal.java

Se crean el paquete swing y la clase VistaPrincipal.

---

JV2016-GruposW/src/modelo/test/MundoTest.java

Añadida la clase Mundo.Test 
By Daniel Martinez Baeza
Grupo 1 DAW

Clase creada Mundo.Test

---

JV2016-GruposW/src/accesoUsr/swing/VistaSesion.java

Se crea la clase VistaSesion.
